// Code generated by protoc-gen-go. DO NOT EDIT.
// source: health.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HealthMessage struct {
	Health               string   `protobuf:"bytes,1,opt,name=health,proto3" json:"health,omitempty"`
	Status               bool     `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthMessage) Reset()         { *m = HealthMessage{} }
func (m *HealthMessage) String() string { return proto.CompactTextString(m) }
func (*HealthMessage) ProtoMessage()    {}
func (*HealthMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdbebe66dda7cb29, []int{0}
}

func (m *HealthMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthMessage.Unmarshal(m, b)
}
func (m *HealthMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthMessage.Marshal(b, m, deterministic)
}
func (m *HealthMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthMessage.Merge(m, src)
}
func (m *HealthMessage) XXX_Size() int {
	return xxx_messageInfo_HealthMessage.Size(m)
}
func (m *HealthMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthMessage.DiscardUnknown(m)
}

var xxx_messageInfo_HealthMessage proto.InternalMessageInfo

func (m *HealthMessage) GetHealth() string {
	if m != nil {
		return m.Health
	}
	return ""
}

func (m *HealthMessage) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterType((*HealthMessage)(nil), "v1.HealthMessage")
}

func init() { proto.RegisterFile("health.proto", fileDescriptor_fdbebe66dda7cb29) }

var fileDescriptor_fdbebe66dda7cb29 = []byte{
	// 123 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0x48, 0x4d, 0xcc,
	0x29, 0xc9, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x33, 0x54, 0xb2, 0xe7, 0xe2,
	0xf5, 0x00, 0x8b, 0xf9, 0xa6, 0x16, 0x17, 0x27, 0xa6, 0xa7, 0x0a, 0x89, 0x71, 0xb1, 0x41, 0x14,
	0x49, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x41, 0x79, 0x20, 0xf1, 0xe2, 0x92, 0xc4, 0x92, 0xd2,
	0x62, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x8e, 0x20, 0x28, 0xcf, 0xc8, 0x9e, 0x8b, 0x0d, 0x62, 0x80,
	0x90, 0x29, 0x17, 0x37, 0x84, 0xe5, 0x9c, 0x91, 0x9a, 0x9c, 0x2d, 0x24, 0xa8, 0x57, 0x66, 0xa8,
	0x87, 0x62, 0xb6, 0x14, 0xa6, 0x90, 0x12, 0x43, 0x12, 0x1b, 0xd8, 0x31, 0xc6, 0x80, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xe7, 0x6d, 0x4f, 0x55, 0x9c, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HealthClient is the client API for Health service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HealthClient interface {
	HealthCheck(ctx context.Context, in *HealthMessage, opts ...grpc.CallOption) (*HealthMessage, error)
}

type healthClient struct {
	cc *grpc.ClientConn
}

func NewHealthClient(cc *grpc.ClientConn) HealthClient {
	return &healthClient{cc}
}

func (c *healthClient) HealthCheck(ctx context.Context, in *HealthMessage, opts ...grpc.CallOption) (*HealthMessage, error) {
	out := new(HealthMessage)
	err := c.cc.Invoke(ctx, "/v1.Health/HealthCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HealthServer is the server API for Health service.
type HealthServer interface {
	HealthCheck(context.Context, *HealthMessage) (*HealthMessage, error)
}

func RegisterHealthServer(s *grpc.Server, srv HealthServer) {
	s.RegisterService(&_Health_serviceDesc, srv)
}

func _Health_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Health/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServer).HealthCheck(ctx, req.(*HealthMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Health_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.Health",
	HandlerType: (*HealthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _Health_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "health.proto",
}
