// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	HealthMessage
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HealthMessage struct {
	Health string `protobuf:"bytes,1,opt,name=health" json:"health,omitempty"`
	Status bool   `protobuf:"varint,2,opt,name=status" json:"status,omitempty"`
}

func (m *HealthMessage) Reset()                    { *m = HealthMessage{} }
func (m *HealthMessage) String() string            { return proto.CompactTextString(m) }
func (*HealthMessage) ProtoMessage()               {}
func (*HealthMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HealthMessage) GetHealth() string {
	if m != nil {
		return m.Health
	}
	return ""
}

func (m *HealthMessage) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterType((*HealthMessage)(nil), "api.HealthMessage")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Health service

type HealthClient interface {
	HealthCheck(ctx context.Context, in *HealthMessage, opts ...grpc.CallOption) (*HealthMessage, error)
}

type healthClient struct {
	cc *grpc.ClientConn
}

func NewHealthClient(cc *grpc.ClientConn) HealthClient {
	return &healthClient{cc}
}

func (c *healthClient) HealthCheck(ctx context.Context, in *HealthMessage, opts ...grpc.CallOption) (*HealthMessage, error) {
	out := new(HealthMessage)
	err := grpc.Invoke(ctx, "/api.Health/HealthCheck", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Health service

type HealthServer interface {
	HealthCheck(context.Context, *HealthMessage) (*HealthMessage, error)
}

func RegisterHealthServer(s *grpc.Server, srv HealthServer) {
	s.RegisterService(&_Health_serviceDesc, srv)
}

func _Health_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Health/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServer).HealthCheck(ctx, req.(*HealthMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Health_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Health",
	HandlerType: (*HealthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _Health_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 124 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2c, 0xc8, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x54, 0xb2, 0xe7, 0xe2, 0xf5, 0x48,
	0x4d, 0xcc, 0x29, 0xc9, 0xf0, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x15, 0x12, 0xe3, 0x62, 0xcb,
	0x00, 0x0b, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x41, 0x79, 0x20, 0xf1, 0xe2, 0x92, 0xc4,
	0x92, 0xd2, 0x62, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x8e, 0x20, 0x28, 0xcf, 0xc8, 0x91, 0x8b, 0x0d,
	0x62, 0x80, 0x90, 0x39, 0x17, 0x37, 0x84, 0xe5, 0x9c, 0x91, 0x9a, 0x9c, 0x2d, 0x24, 0xa4, 0x07,
	0xb2, 0x0a, 0xc5, 0x70, 0x29, 0x2c, 0x62, 0x4a, 0x0c, 0x49, 0x6c, 0x60, 0xf7, 0x18, 0x03, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x79, 0x53, 0xfc, 0xdf, 0x9c, 0x00, 0x00, 0x00,
}
